### PR TITLE
VMTests rework

### PR DESCRIPTION
**Pull request by mersinvald**
This PR updates the testsuit bringing new changes in the `etheriumproject/go-etherium` into the `SputnikVM`.

Currently unresolved issues:
- `inputlimits` tests are currently panicking inside `ethcommon-bigint` on the input size assertion. It happend in the `blockchain.rs` test runtime file, as `difficulty` field seems to be too bit for U256
UPD: might difficulty be defined in base 10?
UPD: looks like vmInpitLimits.json was misgenerated with decimal values in many fields, which causes trouble for the current testing runtime while that's not a problem for `geth`, as it parses numbers through `big.Int`. `U256` from `ethcommon-bigint` expects only base 16 values.
UPD: partially fixed (for Gas and Balance) through replicating `geth`-like values parsing logic

### CODE REVIEW

**Comment by mersinvald** [comment]
I'm going to branch from this PR to fix failing tests after the issues described above are resolved.

**Comment by rocky** [comment]
It is not clear to me whether this copies existing updated ethereum tests or these are new tests. 

But In the long run, I think using the ethereum test unmodifed will be more scalable as PR 29 does.

**Comment by splix** [comment]
@rocky there're few ETH tests that are not applicable to ETC. For example a test for TheDAO transaction reversal, of course that test would fail on ETC. While SputnikVM is supposed to be compatible with any Ethereum-based blockchain, it still unlikely we'll have unmodified ETH tests, bur rather tests based on it with some modifications

**Comment by rocky** [comment]
Ok, got it. But I think the way to handle something like that would be to have some sort of configuration (e.g a configuration file) which indicates which tests to skip. That also serves as a benefit for making explicit that certain tests are not applicable, which seems to currently be implicit.

The important parts of PR 29 were not hardcoding test names into the test, but have that get pulled in externally.

**Comment by mersinvald** [comment]
@rocky I've read through the changes in #332 and in my opinion the approach inherited from ETH test suit is more future-proof and easier to maintain. There are tests rework and extension planned in SputnikVM and we're likely to revisit this PR in the future.

As for now, we just need our tests to be up-to-date with the `geth` and have possible bugs fixed, hence my PR is just a little iteration over the work that've been done in the past, it doesn't contradict with the deeper rework of `SputnikVM` test framework that you're proposing.

P.S also I'm a new member on the team and updating the tests helps a lot with codebase understanding :)

**Comment by rocky** [comment]
Sure - that make sense.

**Comment by mersinvald** [comment]
Also worth noting that after fixing env1 test there will be bunch of tests still failing, like the RecursionBomb tests in the system.rs.
If these are negative tests, need adjustments in test-runner to test them properly.

**Comment by mersinvald** [comment]
Finished, ready for review @splix @r8d8

**Comment by mersinvald** [comment]
Rebased onto master

UPDATE: suggesting a squash-merge, we might not want all the (now removed) tests to add up to repository weight in master

**Review by r8d8 — APPROVED** [review]

**Pull request merged**
