### PR TITLE
Problem: no hello world for regression test

### PR DESCRIPTION
**Pull request by sjmackenzie**
Solution: the db now correctly opens. Also provide steps to
reproduce printed to the console so other people don't have
to suffer the large amounts of time getting a blockchain
on the harddrive.

### CODE REVIEW

**Comment by sjmackenzie** [comment]
rocksdb build time seems to push past the 10min timeout. sigh

**Comment by sorpaas** [comment]
`rocksdb` is GPL, cannot merge.... Linking a GPL library requires distribute under GPL-compatible license. Any alternatives?

**Comment by sjmackenzie** [comment]
Hmm the client is Apache 2 (https://github.com/spacejam/rust-rocksdb/blob/master/LICENSE).

**Comment by sorpaas** [comment]
Okay, sorry I misunderstood. `rocksdb` uses BSD. The newest version has GPL as an alternative license. So this should be fine. Thanks!

**Pull request merged**
