### PR TITLE
Problem: stable only tested

### PR DESCRIPTION
**Pull request by sjmackenzie**
Solution: revert back to travis directly

will be --forcing till I get travis to cooperate, so please don't merge

### CODE REVIEW

**Comment by sjmackenzie** [comment]
notice how long it takes to run travis? It's mental and one of the main reasons why I switched *from* travis to nix.

**Comment by sorpaas** [comment]
Yeah it looks strange, Travis always takes around 20-30 minutes to start the build. I'm guess they're out of computation powers.... But I guess we probably don't have any fix for this issue at least recently.

**Comment by sjmackenzie** [comment]
yeah nix was started pretty quickly. I suspect that's cause they dedicated a machine to nix builds... and as there aren't many nix builds (compared to other builds) the process was started much quicker. Anyway let's see.

**Comment by sorpaas** [comment]
And just throw an idea: if we want to keep using Nix, this can be done by creating multiple nix build using different Rust version. As we're already using the rust overlay, this shouldn't be really hard. We can have `rustChannels.stable.rust` and `rustChannels.beta.rust`.

**Comment by sjmackenzie** [comment]
The problem comes when you separate `gaslighter` and `sputnikvm`. The src is now copied to a derivation and thus a relative path no longer is applicable. Indeed this was a reason for designing `nixcrates`. `nixcrates` solves this issue. I've nearly got it anyway so... lets see.

**Comment by sjmackenzie** [comment]
I'd rather we not swap and change all the time. It's extremely painful working with travis, So given your wish of separating `gaslighter` and `sputnikvm` and building with `stable`, `beta` and `nightly` the best way forward is via travis(ty).

**Pull request merged**
