### PR TITLE
Use crypto and a fork of markle for SHA3

### PR DESCRIPTION
**Pull request by sorpaas**
See commits for details. Note that `rust-crypto` is MIT or Apache licensed.

### CODE REVIEW

**Comment by sorpaas** [comment]
Well, this again breaks nix build because of a git dependency. Any long-term solution for this? @sjmackenzie

**Comment by sjmackenzie** [comment]
Kinda annoying yes, `clap` likes to bump regularly. We could use a more slow moving `docopts` if you wish?
But once dependency version churn slows then we're good. Or we could pin `clap` at a specific vsn and be done with it. I'll fix this issue now.

**Comment by sjmackenzie** [comment]
https://crates.io/crates/clap (notice the 5 hours)

**Comment by sjmackenzie** [comment]
Also every time we change `Cargo.lock` expect that there are dependencies that are available on your local `~/.cargo/*` that are not available on the nixpkgs `rustRegistry` hence we need to bump the rust registry over at https://github.com/sjmackenzie/nixpkgs/tree/rustRegistry_bump. Just nix offers us a nice way to do all sorts of out of band testing and etc. So to me this is a minor pain to endure.

**Comment by sjmackenzie** [comment]
Okay this is going to be bad: -> https://github.com/ethereumproject/sputnikvm/blob/master/Cargo.toml#L26
Nix really doesn't play well with `git` attributes in the `Cargo.toml` file. I'd prefer if we didn't do it this way.

Is it possible to not use git attributes in Cargo.toml?

**Pull request merged**
