### PR TITLE
EIP198 implementation

### PR DESCRIPTION
**Pull request by sorpaas**
Summary:
This adds bigint modular exponentiation precompiled contract definition.

### CODE REVIEW

**Comment by sorpaas** [comment]
@ethereumproject/etcdev-team Please review

**Comment by whilei** [comment]
Tests? Are there any preexisting or included ensuring expected==got, or? 

Also, just for convenience: https://github.com/ethereum/EIPs/pull/198/files

**Comment by sorpaas** [comment]
@whilei Thanks for the review!

I won't be able to add those unit tests in this PR though, due to [subsequent changes](https://source.that.world/source/evm-rs/history/master/) completely moving it off. If you're asking how all Byzantium EIPs are going to be tested, the plan is to conduct a regression test using etclient (or if I didn't get SharedSecret into libsecp256k1 on time, Parity).

**Comment by whilei** [comment]
Aha, gotcha ✅

**Review by whilei — APPROVED** [review]

**Pull request merged**
