### PR TITLE
Missing EIP Specification Testcases

### PR DESCRIPTION
**Pull request by sorpaas**
Summary:
Adds EIP140 and EIP198 testcases borrowed from the specification, and fixes edge case errors.
* EIP198: Fix several overflow problem in gas calculation.
* EIP140: Fix the case in ContextVM where AccountState is not properly reset for REVERT opcode.

### CODE REVIEW

**Comment by sorpaas** [comment]
Fix #312

**Comment by whilei** [comment]
How can I be most useful and helpful to you in a review? I obviously have limited rust knowledge and experience, but if I can be particularly helpful to you here (and in other reviews) in some way please let me know :)

**Comment by sorpaas** [comment]
@whilei I don't particularly have anything for this PR, but here's a list of something that I usually missed / caused trouble before:

* Type `U256` and `Gas` overflow and underflow problem: any `+` / `*` / `-` in the code has a potential problem that it might overflow `U256::max_value()` or underflow `0`. For many times, there's a long execution chain that one can use to reason that the overflow or underflow will never happen (many cases in `AccountState`). However, such thing can be a little more common when calculating gas and before gas is compared with the gas limit. Like you see in L61 of ` precompiled/modexp/src/lib.rs` in this PR.
* Logical change: sometimes I might miss several side effects or make some side effects in vain, especially dealing with clones and moves of `AccountState`.
* Code design: such as `lifecycle.rs`. You can see that `initialize_call` and `initialize_create` only touches the `AccountState`, but it requires the `Machine` context be created prior to anything else. So to accommodate `fresh_account_state` in `ContextVM`, I needed to introduce a new constructor `with_init` that sets `fresh_account_state` again after customized initialization code (used in `TransactionVM`). I don't have an alternative design for this, so I just choose `with_init` because it's the thing that uses the least amount of code as I can think of.

**Review by whilei — APPROVED** [review]
Got it. Thanks for the info, that's definitely some helpful context. 

For my own notes: here's just a quick link to the over/underflow example you mentioned above https://github.com/ethereumproject/sputnikvm/pull/316/files#diff-140cfbaed5bba2bea5703ec3aeef2fe0L61

**Pull request merged**
