### PR TITLE
Problem: rocksdb times out travis

### PR DESCRIPTION
**Pull request by sjmackenzie**
Solution: remove rocksdb, also add new tests

### CODE REVIEW

**Comment by sjmackenzie** [comment]
fixing, don't merge

**Comment by sorpaas** [comment]
Is it good to merge?

**Comment by sjmackenzie** [comment]
@sorpaas seems the issue https://github.com/ethereumproject/sputnikvm/issues/79 is moot?

**Comment by sjmackenzie** [comment]
yes it's good to go

**Pull request merged**
